/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package one.talon.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import one.talon.api.model.ApplicationEntity;
import one.talon.api.model.CartItem;
import one.talon.api.model.IntegrationEntity;
import one.talon.api.model.NewCustomerSession;
import org.joda.time.DateTime;


/**
 * CustomerSession
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T15:56:59.644+02:00")
public class CustomerSession   {
  @SerializedName("firstSession")
  private Boolean firstSession = null;

  @SerializedName("discounts")
  private Map<String, BigDecimal> discounts = new HashMap<String, BigDecimal>();

  public CustomerSession firstSession(Boolean firstSession) {
    this.firstSession = firstSession;
    return this;
  }

   /**
   * Indicates whether this is the first session for the profile. Will always be true for anonymous sessions.
   * @return firstSession
  **/
  @ApiModelProperty(example = "null", value = "Indicates whether this is the first session for the profile. Will always be true for anonymous sessions.")
  public Boolean getFirstSession() {
    return firstSession;
  }

  public void setFirstSession(Boolean firstSession) {
    this.firstSession = firstSession;
  }

  public CustomerSession discounts(Map<String, BigDecimal> discounts) {
    this.discounts = discounts;
    return this;
  }

  public CustomerSession putDiscountsItem(String key, BigDecimal discountsItem) {
    this.discounts.put(key, discountsItem);
    return this;
  }

   /**
   * A map of labelled discount values, values will be in the same currency as the application associated with the session.
   * @return discounts
  **/
  @ApiModelProperty(example = "null", value = "A map of labelled discount values, values will be in the same currency as the application associated with the session.")
  public Map<String, BigDecimal> getDiscounts() {
    return discounts;
  }

  public void setDiscounts(Map<String, BigDecimal> discounts) {
    this.discounts = discounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerSession customerSession = (CustomerSession) o;
    return Objects.equals(this.firstSession, customerSession.firstSession) &&
        Objects.equals(this.discounts, customerSession.discounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstSession, discounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerSession {\n");
    
    sb.append("    firstSession: ").append(toIndentedString(firstSession)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

