/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package one.talon.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import one.talon.api.model.IntegrationEntity;
import one.talon.api.model.NewCustomerProfile;
import org.joda.time.DateTime;


/**
 * CustomerProfile
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T15:56:59.644+02:00")
public class CustomerProfile   {
  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("closedSessions")
  private Integer closedSessions = null;

  @SerializedName("totalSales")
  private BigDecimal totalSales = null;

  @SerializedName("loyaltyPoints")
  private BigDecimal loyaltyPoints = null;

  @SerializedName("advocatePoints")
  private BigDecimal advocatePoints = null;

  @SerializedName("lastActivity")
  private DateTime lastActivity = null;

  public CustomerProfile accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * The ID of the Talon.One account that owns this profile.
   * @return accountId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The ID of the Talon.One account that owns this profile.")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public CustomerProfile closedSessions(Integer closedSessions) {
    this.closedSessions = closedSessions;
    return this;
  }

   /**
   * Get closedSessions
   * @return closedSessions
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getClosedSessions() {
    return closedSessions;
  }

  public void setClosedSessions(Integer closedSessions) {
    this.closedSessions = closedSessions;
  }

  public CustomerProfile totalSales(BigDecimal totalSales) {
    this.totalSales = totalSales;
    return this;
  }

   /**
   * Get totalSales
   * @return totalSales
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public BigDecimal getTotalSales() {
    return totalSales;
  }

  public void setTotalSales(BigDecimal totalSales) {
    this.totalSales = totalSales;
  }

  public CustomerProfile loyaltyPoints(BigDecimal loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
    return this;
  }

   /**
   * A point score for use in campaign rules.
   * @return loyaltyPoints
  **/
  @ApiModelProperty(example = "null", required = true, value = "A point score for use in campaign rules.")
  public BigDecimal getLoyaltyPoints() {
    return loyaltyPoints;
  }

  public void setLoyaltyPoints(BigDecimal loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
  }

  public CustomerProfile advocatePoints(BigDecimal advocatePoints) {
    this.advocatePoints = advocatePoints;
    return this;
  }

   /**
   * Get advocatePoints
   * @return advocatePoints
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public BigDecimal getAdvocatePoints() {
    return advocatePoints;
  }

  public void setAdvocatePoints(BigDecimal advocatePoints) {
    this.advocatePoints = advocatePoints;
  }

  public CustomerProfile lastActivity(DateTime lastActivity) {
    this.lastActivity = lastActivity;
    return this;
  }

   /**
   * Timestamp of the most recent event received from this customer
   * @return lastActivity
  **/
  @ApiModelProperty(example = "null", required = true, value = "Timestamp of the most recent event received from this customer")
  public DateTime getLastActivity() {
    return lastActivity;
  }

  public void setLastActivity(DateTime lastActivity) {
    this.lastActivity = lastActivity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerProfile customerProfile = (CustomerProfile) o;
    return Objects.equals(this.accountId, customerProfile.accountId) &&
        Objects.equals(this.closedSessions, customerProfile.closedSessions) &&
        Objects.equals(this.totalSales, customerProfile.totalSales) &&
        Objects.equals(this.loyaltyPoints, customerProfile.loyaltyPoints) &&
        Objects.equals(this.advocatePoints, customerProfile.advocatePoints) &&
        Objects.equals(this.lastActivity, customerProfile.lastActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, closedSessions, totalSales, loyaltyPoints, advocatePoints, lastActivity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerProfile {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    closedSessions: ").append(toIndentedString(closedSessions)).append("\n");
    sb.append("    totalSales: ").append(toIndentedString(totalSales)).append("\n");
    sb.append("    loyaltyPoints: ").append(toIndentedString(loyaltyPoints)).append("\n");
    sb.append("    advocatePoints: ").append(toIndentedString(advocatePoints)).append("\n");
    sb.append("    lastActivity: ").append(toIndentedString(lastActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

