/**
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package one.talon.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PaymentProfile
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T15:56:59.644+02:00")
public class PaymentProfile   {
  @SerializedName("billingSalutation")
  private String billingSalutation = null;

  @SerializedName("billingName")
  private String billingName = null;

  @SerializedName("billingAddress1")
  private String billingAddress1 = null;

  @SerializedName("billingAddress2")
  private String billingAddress2 = null;

  @SerializedName("billingAddress3")
  private String billingAddress3 = null;

  @SerializedName("billingAddress4")
  private String billingAddress4 = null;

  @SerializedName("billingCity")
  private String billingCity = null;

  @SerializedName("billingPostalCode")
  private String billingPostalCode = null;

  @SerializedName("billingCountry")
  private String billingCountry = null;

  @SerializedName("shippingSalutation")
  private String shippingSalutation = null;

  @SerializedName("shippingName")
  private String shippingName = null;

  @SerializedName("shippingAddress1")
  private String shippingAddress1 = null;

  @SerializedName("shippingAddress2")
  private String shippingAddress2 = null;

  @SerializedName("shippingAddress3")
  private String shippingAddress3 = null;

  @SerializedName("shippingAddress4")
  private String shippingAddress4 = null;

  @SerializedName("shippingCity")
  private String shippingCity = null;

  @SerializedName("shippingPostalCode")
  private String shippingPostalCode = null;

  @SerializedName("shippingCountry")
  private String shippingCountry = null;

  @SerializedName("paymentMethod")
  private String paymentMethod = null;

  @SerializedName("paymentIdHash")
  private String paymentIdHash = null;

  public PaymentProfile billingSalutation(String billingSalutation) {
    this.billingSalutation = billingSalutation;
    return this;
  }

   /**
   * Get billingSalutation
   * @return billingSalutation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingSalutation() {
    return billingSalutation;
  }

  public void setBillingSalutation(String billingSalutation) {
    this.billingSalutation = billingSalutation;
  }

  public PaymentProfile billingName(String billingName) {
    this.billingName = billingName;
    return this;
  }

   /**
   * Get billingName
   * @return billingName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingName() {
    return billingName;
  }

  public void setBillingName(String billingName) {
    this.billingName = billingName;
  }

  public PaymentProfile billingAddress1(String billingAddress1) {
    this.billingAddress1 = billingAddress1;
    return this;
  }

   /**
   * Get billingAddress1
   * @return billingAddress1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingAddress1() {
    return billingAddress1;
  }

  public void setBillingAddress1(String billingAddress1) {
    this.billingAddress1 = billingAddress1;
  }

  public PaymentProfile billingAddress2(String billingAddress2) {
    this.billingAddress2 = billingAddress2;
    return this;
  }

   /**
   * Get billingAddress2
   * @return billingAddress2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingAddress2() {
    return billingAddress2;
  }

  public void setBillingAddress2(String billingAddress2) {
    this.billingAddress2 = billingAddress2;
  }

  public PaymentProfile billingAddress3(String billingAddress3) {
    this.billingAddress3 = billingAddress3;
    return this;
  }

   /**
   * Get billingAddress3
   * @return billingAddress3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingAddress3() {
    return billingAddress3;
  }

  public void setBillingAddress3(String billingAddress3) {
    this.billingAddress3 = billingAddress3;
  }

  public PaymentProfile billingAddress4(String billingAddress4) {
    this.billingAddress4 = billingAddress4;
    return this;
  }

   /**
   * Get billingAddress4
   * @return billingAddress4
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingAddress4() {
    return billingAddress4;
  }

  public void setBillingAddress4(String billingAddress4) {
    this.billingAddress4 = billingAddress4;
  }

  public PaymentProfile billingCity(String billingCity) {
    this.billingCity = billingCity;
    return this;
  }

   /**
   * Get billingCity
   * @return billingCity
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingCity() {
    return billingCity;
  }

  public void setBillingCity(String billingCity) {
    this.billingCity = billingCity;
  }

  public PaymentProfile billingPostalCode(String billingPostalCode) {
    this.billingPostalCode = billingPostalCode;
    return this;
  }

   /**
   * Get billingPostalCode
   * @return billingPostalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingPostalCode() {
    return billingPostalCode;
  }

  public void setBillingPostalCode(String billingPostalCode) {
    this.billingPostalCode = billingPostalCode;
  }

  public PaymentProfile billingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
    return this;
  }

   /**
   * Get billingCountry
   * @return billingCountry
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingCountry() {
    return billingCountry;
  }

  public void setBillingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
  }

  public PaymentProfile shippingSalutation(String shippingSalutation) {
    this.shippingSalutation = shippingSalutation;
    return this;
  }

   /**
   * Get shippingSalutation
   * @return shippingSalutation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingSalutation() {
    return shippingSalutation;
  }

  public void setShippingSalutation(String shippingSalutation) {
    this.shippingSalutation = shippingSalutation;
  }

  public PaymentProfile shippingName(String shippingName) {
    this.shippingName = shippingName;
    return this;
  }

   /**
   * Get shippingName
   * @return shippingName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingName() {
    return shippingName;
  }

  public void setShippingName(String shippingName) {
    this.shippingName = shippingName;
  }

  public PaymentProfile shippingAddress1(String shippingAddress1) {
    this.shippingAddress1 = shippingAddress1;
    return this;
  }

   /**
   * Get shippingAddress1
   * @return shippingAddress1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingAddress1() {
    return shippingAddress1;
  }

  public void setShippingAddress1(String shippingAddress1) {
    this.shippingAddress1 = shippingAddress1;
  }

  public PaymentProfile shippingAddress2(String shippingAddress2) {
    this.shippingAddress2 = shippingAddress2;
    return this;
  }

   /**
   * Get shippingAddress2
   * @return shippingAddress2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingAddress2() {
    return shippingAddress2;
  }

  public void setShippingAddress2(String shippingAddress2) {
    this.shippingAddress2 = shippingAddress2;
  }

  public PaymentProfile shippingAddress3(String shippingAddress3) {
    this.shippingAddress3 = shippingAddress3;
    return this;
  }

   /**
   * Get shippingAddress3
   * @return shippingAddress3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingAddress3() {
    return shippingAddress3;
  }

  public void setShippingAddress3(String shippingAddress3) {
    this.shippingAddress3 = shippingAddress3;
  }

  public PaymentProfile shippingAddress4(String shippingAddress4) {
    this.shippingAddress4 = shippingAddress4;
    return this;
  }

   /**
   * Get shippingAddress4
   * @return shippingAddress4
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingAddress4() {
    return shippingAddress4;
  }

  public void setShippingAddress4(String shippingAddress4) {
    this.shippingAddress4 = shippingAddress4;
  }

  public PaymentProfile shippingCity(String shippingCity) {
    this.shippingCity = shippingCity;
    return this;
  }

   /**
   * Get shippingCity
   * @return shippingCity
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingCity() {
    return shippingCity;
  }

  public void setShippingCity(String shippingCity) {
    this.shippingCity = shippingCity;
  }

  public PaymentProfile shippingPostalCode(String shippingPostalCode) {
    this.shippingPostalCode = shippingPostalCode;
    return this;
  }

   /**
   * Get shippingPostalCode
   * @return shippingPostalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingPostalCode() {
    return shippingPostalCode;
  }

  public void setShippingPostalCode(String shippingPostalCode) {
    this.shippingPostalCode = shippingPostalCode;
  }

  public PaymentProfile shippingCountry(String shippingCountry) {
    this.shippingCountry = shippingCountry;
    return this;
  }

   /**
   * Get shippingCountry
   * @return shippingCountry
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingCountry() {
    return shippingCountry;
  }

  public void setShippingCountry(String shippingCountry) {
    this.shippingCountry = shippingCountry;
  }

  public PaymentProfile paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public PaymentProfile paymentIdHash(String paymentIdHash) {
    this.paymentIdHash = paymentIdHash;
    return this;
  }

   /**
   * Get paymentIdHash
   * @return paymentIdHash
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentIdHash() {
    return paymentIdHash;
  }

  public void setPaymentIdHash(String paymentIdHash) {
    this.paymentIdHash = paymentIdHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentProfile paymentProfile = (PaymentProfile) o;
    return Objects.equals(this.billingSalutation, paymentProfile.billingSalutation) &&
        Objects.equals(this.billingName, paymentProfile.billingName) &&
        Objects.equals(this.billingAddress1, paymentProfile.billingAddress1) &&
        Objects.equals(this.billingAddress2, paymentProfile.billingAddress2) &&
        Objects.equals(this.billingAddress3, paymentProfile.billingAddress3) &&
        Objects.equals(this.billingAddress4, paymentProfile.billingAddress4) &&
        Objects.equals(this.billingCity, paymentProfile.billingCity) &&
        Objects.equals(this.billingPostalCode, paymentProfile.billingPostalCode) &&
        Objects.equals(this.billingCountry, paymentProfile.billingCountry) &&
        Objects.equals(this.shippingSalutation, paymentProfile.shippingSalutation) &&
        Objects.equals(this.shippingName, paymentProfile.shippingName) &&
        Objects.equals(this.shippingAddress1, paymentProfile.shippingAddress1) &&
        Objects.equals(this.shippingAddress2, paymentProfile.shippingAddress2) &&
        Objects.equals(this.shippingAddress3, paymentProfile.shippingAddress3) &&
        Objects.equals(this.shippingAddress4, paymentProfile.shippingAddress4) &&
        Objects.equals(this.shippingCity, paymentProfile.shippingCity) &&
        Objects.equals(this.shippingPostalCode, paymentProfile.shippingPostalCode) &&
        Objects.equals(this.shippingCountry, paymentProfile.shippingCountry) &&
        Objects.equals(this.paymentMethod, paymentProfile.paymentMethod) &&
        Objects.equals(this.paymentIdHash, paymentProfile.paymentIdHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingSalutation, billingName, billingAddress1, billingAddress2, billingAddress3, billingAddress4, billingCity, billingPostalCode, billingCountry, shippingSalutation, shippingName, shippingAddress1, shippingAddress2, shippingAddress3, shippingAddress4, shippingCity, shippingPostalCode, shippingCountry, paymentMethod, paymentIdHash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentProfile {\n");
    
    sb.append("    billingSalutation: ").append(toIndentedString(billingSalutation)).append("\n");
    sb.append("    billingName: ").append(toIndentedString(billingName)).append("\n");
    sb.append("    billingAddress1: ").append(toIndentedString(billingAddress1)).append("\n");
    sb.append("    billingAddress2: ").append(toIndentedString(billingAddress2)).append("\n");
    sb.append("    billingAddress3: ").append(toIndentedString(billingAddress3)).append("\n");
    sb.append("    billingAddress4: ").append(toIndentedString(billingAddress4)).append("\n");
    sb.append("    billingCity: ").append(toIndentedString(billingCity)).append("\n");
    sb.append("    billingPostalCode: ").append(toIndentedString(billingPostalCode)).append("\n");
    sb.append("    billingCountry: ").append(toIndentedString(billingCountry)).append("\n");
    sb.append("    shippingSalutation: ").append(toIndentedString(shippingSalutation)).append("\n");
    sb.append("    shippingName: ").append(toIndentedString(shippingName)).append("\n");
    sb.append("    shippingAddress1: ").append(toIndentedString(shippingAddress1)).append("\n");
    sb.append("    shippingAddress2: ").append(toIndentedString(shippingAddress2)).append("\n");
    sb.append("    shippingAddress3: ").append(toIndentedString(shippingAddress3)).append("\n");
    sb.append("    shippingAddress4: ").append(toIndentedString(shippingAddress4)).append("\n");
    sb.append("    shippingCity: ").append(toIndentedString(shippingCity)).append("\n");
    sb.append("    shippingPostalCode: ").append(toIndentedString(shippingPostalCode)).append("\n");
    sb.append("    shippingCountry: ").append(toIndentedString(shippingCountry)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentIdHash: ").append(toIndentedString(paymentIdHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

